<a href="https://colab.research.google.com/github/Papijohan000/colab_IA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np

m=np.array([1,2,4])
print(m)
print(m.shape)
m=np.array([[1,2,4],[1,2,4]])
print(m.shape)
print(m)
print(type(m))

x=np.zeros((4,4))
print('-----------')
print(x)


x=np.full((4,4),5)
print(x)


x=np.eye(4,4)
print(x)


x=np.ones((4,4))
print(x)

print(x.shape)

[1 2 4]
(3,)
(2, 3)
[[1 2 4]
 [1 2 4]]
<class 'numpy.ndarray'>
-----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [36]:
x=10*np.random.random((3,3))
print(x)

[[1.09418452 5.11091821 6.89561369]
 [4.47491341 3.97686112 0.44221704]
 [1.75207156 0.13680686 3.3901382 ]]


In [37]:
print(x[:2,:2])

[[1.09418452 5.11091821]
 [4.47491341 3.97686112]]


In [38]:
print(x[:2,1:3])

[[5.11091821 6.89561369]
 [3.97686112 0.44221704]]


In [39]:
print(x[1,1])

3.9768611177827506


In [40]:
print(x[2,2])

3.390138203808185


In [41]:
x=10*np.random.random((3,3))
print(x)

[[7.45820608 7.0590548  4.92599141]
 [0.25904906 1.1323241  2.5013481 ]
 [8.36261487 6.89203021 6.22809217]]


In [42]:
mask=x>5
print(x[mask])

[7.45820608 7.0590548  8.36261487 6.89203021 6.22809217]


In [43]:
filter=(x>=2)&(x<=4)
print(x[filter])

[2.5013481]


In [44]:
filter=(x>=2)&(x<=4)
print(x[filter])

[2.5013481]


NUMPY_CLASE2

In [45]:

a=np.random.randint(0,10,(3,4))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
print(a)
print("MATRIZ B")
print(b)

print("SUMANDO")
print(a+b)
print("RESTANDO")
print(a-b)
print("MULTIPLICANDO")
print(a*b)

print(np.add(a,b))
print("___________")

print(np.multiply(a,b))
print("___________")

print(np.divide(a,b))
print("___________")


MATRIZ A
[[8 6 3 5]
 [9 6 6 3]
 [8 6 7 5]]
MATRIZ B
[[5 9 1 3]
 [6 3 2 1]
 [0 7 3 1]]
SUMANDO
[[13 15  4  8]
 [15  9  8  4]
 [ 8 13 10  6]]
RESTANDO
[[ 3 -3  2  2]
 [ 3  3  4  2]
 [ 8 -1  4  4]]
MULTIPLICANDO
[[40 54  3 15]
 [54 18 12  3]
 [ 0 42 21  5]]
[[13 15  4  8]
 [15  9  8  4]
 [ 8 13 10  6]]
___________
[[40 54  3 15]
 [54 18 12  3]
 [ 0 42 21  5]]
___________
[[1.6        0.66666667 3.         1.66666667]
 [1.5        2.         3.         3.        ]
 [       inf 0.85714286 2.33333333 5.        ]]
___________


<ipython-input-45-dc213cc313db>:22: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


In [46]:
# random.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(2,3))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
print(a)
print("MATRIZ B")
print(b)
print("___________")

# dot son multiplica las matrices
print(np.dot(a,b))

MATRIZ A
[[7 9 5]
 [7 5 4]]
MATRIZ B
[[6 1 6 6]
 [9 2 9 3]
 [1 6 9 6]]
___________
[[128  55 168  99]
 [ 91  41 123  81]]


In [47]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a.T)

[[4 2 1]
 [8 8 5]
 [4 1 9]]
[[4 8 4]
 [2 8 1]
 [1 5 9]]


In [48]:
a=np.random.randint(0,10,(4,3))
print(a)


b=np.array([1,0,2])
print(b)

c=np.empty_like(a)
print(c)

x=a+b

print(np.empty_like(x))

[[5 9 4]
 [5 9 4]
 [6 4 0]
 [9 3 1]]
[1 0 2]
[[4609884578576439706 4604180019048437077 4613937818241073152]
 [4610184818551597739 4609434218613702656 4611686018427387904]
 [4613937818241073152 4613937818241073152 9218868437227405312]
 [4605895676049340123 4612436618365282987 4617315517961601024]]
[[4601392076421969627 4597174419628082972 4607182418800017408]
 [4603179219131243634 4608469161550694693 4621256167635550208]
 [4608469161550694693 4616189618054758400 4594314991293244562]
 [4604180019048437077 4608683618675807573 4598175219545276416]]


In [49]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)



print(b)



print(c)


[[5 9 4]
 [5 9 4]
 [6 4 0]
 [9 3 1]]
[1 0 2]
[[ 6  9  6]
 [ 6  9  6]
 [ 7  4  2]
 [10  3  3]]


In [52]:
b=np.array([1,2,3])
print(b)
x=np.tile(b,(6,1))
print(x)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
a=np.random.randint(20,31,(6,6))
print(a)

print("PROMEDIOS COMPLETOS")
m1=np.mean(a)
print(m1)

print("PROMEDIOS POR FILAS")
m2=np.mean(a,axis=1)
print(m2)

[[26 28 21 20 23 23]
 [26 23 20 25 24 24]
 [28 22 29 21 28 30]
 [20 28 21 29 27 26]
 [30 24 24 21 28 30]
 [30 30 23 30 30 21]]
PROMEDIOS COMPLETOS
25.36111111111111
PROMEDIOS POR FILAS
[23.5        23.66666667 26.33333333 25.16666667 26.16666667 27.33333333]
